packages:
  - apps/*
  - packages/*
allowBuilds:
  "@prisma/engines": true
  better-sqlite3: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - shadcn@4.16.1
